"""发送端和接收端共用的 GenX320 RGB 同步协议参数。"""

PROTOCOL_VERSION = "rgb-sync-v1"
CHANNEL_ID = 0

TOTAL_DURATION = 15.0
RGB_INTERVAL_S = 0.100
RGB_INTERVAL_US = round(RGB_INTERVAL_S * 1_000_000)
EXPECTED_RGB_PULSES = round(TOTAL_DURATION / RGB_INTERVAL_S)

TRIGGER_PULSE_WIDTH_S = 0.002
MARKER_INTERVAL_S = 0.030
MARKER_INTERVAL_US = round(MARKER_INTERVAL_S * 1_000_000)
PREAMBLE_PULSES = 3
PREAMBLE_GUARD_S = 0.500
START_PULSES = 2
START_TO_DATA_GUARD_S = 0.300
DATA_TO_STOP_GUARD_S = 0.300
STOP_PULSES = 4
